---
title: "Participants dataset dictionary"
output:
  html_document:
    toc: true
    toc_depth: 4
    toc_float: true
    code_folding: 'hide'
    self_contained: true
  pdf_document:
    toc: yes
    toc_depth: 4
    latex_engine: xelatex
---


```{r setup}
knitr::opts_chunk$set(
  warning = TRUE, # show warnings during codebook generation
  message = TRUE, # show messages during codebook generation
  error = TRUE, # do not interrupt codebook generation in case of errors,
                # usually better for debugging
  echo = TRUE  # show R code
)
# load all required libraries using the groundhog package (installs libraries that are not installed yet)
source("groundhog_packages.R")

ggplot2::theme_set(ggplot2::theme_bw())
pander::panderOptions("table.split.table", Inf)
```



```{r message=FALSE, warning=FALSE}
#load dataset
study_1_part <- readRDS(here::here("03_output","processed_data", "study1_participants_anonymized.Rdata"))

```

```{r add_metadata}

metadata(study_1_part)$name = "Participants file for Manuscript _Fine-tuning Language Discrimination_ (Study 1)"
metadata(study_1_part)$description = "Demographic info and details on participation for participants in  Manuscript _Fine-tuning Language Discrimination_. This particular codebook was created for the participants in Study 1, but the columns in Study 2 are largely overlapping (and even when content is not the same, the column names and content types are the same)"

```

```{r var_explanations}

var_label(study_1_part$part_id) = "Anonymous Participant ID"

var_label(study_1_part$age_days) = "Age in Days" 

var_label(study_1_part$lang_group) = "Language Background : Monolingual vs. Bilingual" 
val_labels(study_1_part$lang_group) = c("Child is bilingual (English-French or English-Spanish" = "bilingual", 
  "Child is monolingual (English or French)" = "monolingual", 
  "Child is neither bilingual nor monolingual" = "other")

var_label(study_1_part$child_dom_lang) = "Language Dominance (based on % language exposure)"
val_labels(study_1_part$child_dom_lang) = c("Child dominant in English" = "English", 
  "Child dominant in French" = "French", 
  "Child dominant in Spanish" = "Spanish")

var_label(study_1_part$test_location_pr) = "Location child was tested (blinded for peer review)"
val_labels(study_1_part$test_location_pr) = c("Test Location 1"="loc1",
                                              "Test Location 2" = "loc2")

var_label(study_1_part$study) = "Study number (in this dataset, 1)"

var_label(study_1_part$gender) = "Gender of participant"
var_label(study_1_part$order) = "Order participant was tested in. Four orders each of English, French, Spanish. English/French orders: E1, E2, E3, E4, F1, F2, F3, F4. English/Spanish orders: e1, e2, e3, e4, s1, s2, s3, s4. See readme on OSF"

var_label(study_1_part$keeper) = "Was participant a keeper for this study?"
val_labels(study_1_part$keeper) = c("Keeper" = 1, "Non-keeper" =0)

var_label(study_1_part$keeper_reason) = "reasons for excluding a participant"
val_labels(study_1_part$keeper) <- c("Run as part of piloting to train experimenter"= "pilot", 
                                     "does not fit pre-defined language criteria"= "language", 
                                     "experimenter error. Combined with teachnical difficulties in paper" = "experimenterError", 
                                     "excluded for not enough good trials after rejecting trials that had a short looking time (see manuscript for cutoff)" = "NotEnoughGoodTrials",
                                    "technical difficulties. Combined with experimenter error in paper" = "technicalDifficulties", 
                                     "born prematurely, health issues affecting language or cognitive development" = "health")
var_label(study_1_part$lang_per_en) = "Percent of Exposure to English"

var_label(study_1_part$lang_per_fr) = "Percent of Exposure to French"

var_label(study_1_part$lang_per_sp) = "Percent of Exposure to Spanish"

var_label(study_1_part$lang_per_ot) = "Percent of Exposure to Other languages (if more than one other language, percentages are summed)"

var_label(study_1_part$study_dom) = "Was participant tested using an order in their dominant or non-dominant language? This means slightly different things for Study 1 and 2
Study 1: single-language trials were in their dominant/non-dominant language
Study 2: Sentence frame was in dominant/non-dominant language.
This has NA for two children who are non-keepers (never started the study due to technical problems)"
#val_label(study_1_part$study_dom) = c("Child was tested using order in dominant language" = "dominant", 
 #                                    "Child was tested using order non-dominant language" ="non-dominant")

var_label(study_1_part$lang_mix_score) = "Score on Language Mixing Scale (Byers-Heinlein, 2013). Max score is 30 (a lot of language mixing)"
var_label(study_1_part$coding_missing) = "Variable indicates whether offline coding is missing for participant in this study"
val_labels(study_1_part$coding_missing) <- c("Offline coding missing" = 1, "Offline coding not missing" = 0)
var_label(study_1_part$N_trials) = "Number of trials completed"
var_label(study_1_part$meanLT) = "Mean looking time for Study 1"
# template to add new variable
#var_label(study_1_part$COL) = "DESC"




```




```{r codebook}
codebook(study_1_part, detailed_variables = F, missingness_report = F)
codebook(study_1_part, survey_overview = F, metadata_table = F)

```
